version: '3'
services:
  mango1:
    image: mario21ic/pylb
    environment:
      - APP=mango
    ports:
      - "8081:5000"
  mango2:
    image: mario21ic/pylb
    environment:
      - APP=mango
    ports:
      - "8082:5000"
  apple1:
    image: mario21ic/pylb
    environment:
      - APP=apple
    ports:
      - "9081:5000"
  apple2:
    image: mario21ic/pylb
    environment:
      - APP=apple
    ports:
      - "9082:5000"

